#!/usr/bin/env python3
"""
bib_to_yaml.py - convert a BibTeX file (e.g. exported from Zotero) into publications.yml

Usage (run from the jaechenique-site folder):

    python3 scripts/bib_to_yaml.py refs.bib                 # writes publications.yml (old one saved as .bak)
    python3 scripts/bib_to_yaml.py refs.bib --dry-run       # print the result, change nothing
    python3 scripts/bib_to_yaml.py refs.bib --replace       # drop entries that are not in the .bib

By default the script MERGES with the existing publications.yml:
  * a paper that is in both (matched by title) keeps its abstract, area, status and link
    from the old file whenever the .bib does not provide them;
  * papers that are only in the old file are kept (use --replace to drop them).

Zotero tips (all optional, set them as Tags on the item):
  type:published | type:working     decides the section (otherwise: has journal + year = published)
  area:Mental Health                heading for working papers
  status:Submitted                  small tag shown next to the title
The "Abstract" field of the Zotero item becomes the expandable abstract.
For papers with a "Extra" or "Notes" field containing "Forthcoming", "Submitted",
"In preparation" or "Under review", the status tag is filled in automatically.

Only the Python standard library is needed (PyYAML is used for --merge if installed).
"""
import argparse
import re
import shutil
import sys
import unicodedata
from pathlib import Path

SELF_LASTNAME = "echenique"          # your name is skipped in "with ..." lists
OUT_DEFAULT = "publications.yml"

HEADER = """# Publications database for research.qmd
# Generated by scripts/bib_to_yaml.py from a .bib file; you can also edit it by hand.
#
# type:     published | working
# area:     (working papers only) heading the paper is grouped under
# status:   optional tag (Forthcoming, Submitted, In preparation, ...)
# doi:      published articles: DOI only, e.g. 10.1016/j.xxxx
# url:      optional extra link (SSRN, PDF, ...), url_text = its label
# abstract: optional; blank lines separate paragraphs. Shown in an expandable box.
# Keep entries in the order you want them displayed.

"""

# ---------------------------------------------------------------- LaTeX cleanup
MARKS = {"'": "\u0301", "`": "\u0300", "^": "\u0302", '"': "\u0308", "~": "\u0303",
         "c": "\u0327", "v": "\u030c"}


def clean(s):
    if s is None:
        return ""
    s = re.sub(r"\\([`'^\"~])\s*\{?\\?([A-Za-z])\}?", lambda m: unicodedata.normalize("NFC", m.group(2) + MARKS[m.group(1)]), s)
    s = re.sub(r"\\([cv])\s*\{([A-Za-z])\}", lambda m: unicodedata.normalize("NFC", m.group(2) + MARKS[m.group(1)]), s)
    s = s.replace("\\&", "&").replace("\\%", "%").replace("\\_", "_").replace("\\$", "$")
    s = re.sub(r"\\(?:textit|emph|textbf|textsc)\{([^{}]*)\}", r"\1", s)
    s = s.replace("---", "—").replace("--", "–").replace("~", " ")
    s = s.replace("{", "").replace("}", "")
    return re.sub(r"\s+", " ", s).strip()


# ---------------------------------------------------------------- BibTeX parser
def parse_fields(body):
    fields, i, n = {}, 0, len(body)
    while i < n:
        m = re.compile(r"\s*,?\s*([A-Za-z][\w:-]*)\s*=\s*").match(body, i)
        if not m:
            break
        name, i = m.group(1).lower(), m.end()
        if i >= n:
            break
        if body[i] == "{":
            depth, j = 1, i + 1
            while j < n and depth:
                depth += (body[j] == "{") - (body[j] == "}")
                j += 1
            value, i = body[i + 1:j - 1], j
        elif body[i] == '"':
            j = i + 1
            while j < n and not (body[j] == '"' and body[j - 1] != "\\"):
                j += 1
            value, i = body[i + 1:j], j + 1
        else:
            m2 = re.compile(r"[^,}\s]+").match(body, i)
            value, i = (m2.group(0), m2.end()) if m2 else ("", i + 1)
        fields[name] = value
    return fields


def parse_bib(text):
    entries, i = [], 0
    while True:
        m = re.compile(r"@(\w+)\s*[{(]").search(text, i)
        if not m:
            break
        etype, start = m.group(1).lower(), m.end()
        depth, j = 1, start
        while j < len(text) and depth:
            depth += (text[j] == "{") - (text[j] == "}")
            j += 1
        body, i = text[start:j - 1], j
        if etype in ("comment", "string", "preamble"):
            continue
        key, _, rest = body.partition(",")
        entries.append({"type": etype, "key": key.strip(), "fields": parse_fields(rest)})
    return entries


# ---------------------------------------------------------------- field mapping
def split_authors(raw):
    people = []
    for a in re.split(r"\s+and\s+", clean_keep_commas(raw)):
        a = a.strip()
        if not a:
            continue
        if "," in a:
            last, first = [x.strip() for x in a.split(",", 1)]
        else:
            parts = a.split()
            last, first = parts[-1], " ".join(parts[:-1])
        people.append((last, first))
    return people


def clean_keep_commas(s):
    return clean(s)


def initials(first):
    toks = [t for t in re.split(r"[\s]+", first) if t]
    out = []
    for t in toks:
        for piece in t.split("-"):
            if piece:
                out.append(piece[0].upper() + ".")
    return " ".join(out)


def authors_published(people):
    names = [f"{last}, {initials(first)}".rstrip(", ").strip() for last, first in people]
    if len(names) <= 1:
        return "".join(names)
    return ", ".join(names[:-1]) + ", & " + names[-1]


def authors_working(people):
    others = [f"{initials(f)} {l}".strip() for l, f in people if l.lower() != SELF_LASTNAME]
    if not others:
        return ""
    if len(others) == 1:
        return "with " + others[0]
    if len(others) == 2:
        return f"with {others[0]} and {others[1]}"
    return "with " + ", ".join(others[:-1]) + ", and " + others[-1]


def tags_of(f):
    raw = clean(f.get("keywords", ""))
    return [t.strip() for t in re.split(r"[;,]", raw) if t.strip()]


def status_from_text(txt):
    t = (txt or "").lower()
    for needle, label in (("forthcoming", "Forthcoming"), ("in press", "Forthcoming"),
                          ("in preparation", "In preparation"), ("in prep", "In preparation"),
                          ("under review", "Under review"), ("revise and resubmit", "Revise & resubmit"),
                          ("submitted", "Submitted")):
        if needle in t:
            return label
    return None


def url_label(url):
    return "SSRN" if "ssrn.com" in url else "arXiv" if "arxiv.org" in url else "Link"


def venue_of(f):
    j = clean(f.get("journal") or f.get("journaltitle") or f.get("booktitle") or f.get("publisher") or "")
    vol, num, pages = clean(f.get("volume", "")), clean(f.get("number", "")), clean(f.get("pages", ""))
    out = j
    if vol:
        out += f", {vol}" + (f"({num})" if num else "")
    if pages:
        out += f", {pages}"
    return out


def convert(entry):
    f = entry["fields"]
    tags = tags_of(f)
    tag = lambda p: next((t.split(":", 1)[1].strip() for t in tags if t.lower().startswith(p + ":")), None)
    note = " ".join(clean(f.get(k, "")) for k in ("note", "annote", "pubstate", "addendum"))
    status = tag("status") or status_from_text(note)
    people = split_authors(f.get("author", ""))
    has_journal = bool(f.get("journal") or f.get("journaltitle"))
    year = clean(f.get("year") or (f.get("date", "")[:4]))
    etype = (tag("type") or "").lower()
    if etype not in ("published", "working"):
        working_status = status in ("Submitted", "In preparation", "Under review", "Revise & resubmit")
        etype = "published" if (has_journal and (year or status == "Forthcoming") and not working_status) else "working"

    d = {"type": etype}
    if etype == "working":
        d["area"] = tag("area") or "Other"
    d["title"] = clean(f.get("title", ""))
    authors = authors_published(people) if etype == "published" else authors_working(people)
    if authors:
        d["authors"] = authors
    if etype == "published":
        d["venue"] = venue_of(f)
        if year and status != "Forthcoming":
            d["year"] = int(year) if year.isdigit() else year
    if status:
        d["status"] = status
    doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", clean(f.get("doi", "")))
    if doi and etype == "published":
        d["doi"] = doi
    url = clean(f.get("url", ""))
    if url and not (etype == "published" and doi):
        d["url"] = url
        d["url_text"] = url_label(url)
    abstract = f.get("abstract", "")
    if abstract:
        paras = [clean(p) for p in re.split(r"\n\s*\n", abstract)]
        d["abstract"] = "\n\n".join(p for p in paras if p)
    return d


# ---------------------------------------------------------------- YAML output (no dependencies)
SAFE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 ,.()/&–'\-]*$")


def scalar(v):
    if isinstance(v, int):
        return str(v)
    v = str(v)
    if SAFE.match(v) and not v.endswith(":") and v.lower() not in ("yes", "no", "true", "false", "null", "on", "off") \
            and not re.fullmatch(r"[\d.]+", v):
        return v
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


ORDER = ["type", "area", "title", "authors", "venue", "year", "status", "note", "doi", "url", "url_text", "abstract"]


def dump(items):
    lines = []
    for d in items:
        keys = [k for k in ORDER if k in d] + [k for k in d if k not in ORDER]
        first = True
        for k in keys:
            prefix = "- " if first else "  "
            first = False
            v = d[k]
            if k == "abstract" or (isinstance(v, str) and "\n" in v):
                lines.append(f"{prefix}{k}: |")
                for para_line in str(v).split("\n"):
                    lines.append(("    " + para_line) if para_line else "")
            else:
                lines.append(f"{prefix}{k}: {scalar(v)}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- merge with existing file
def norm(t):
    return re.sub(r"[^a-z0-9]+", " ", t.lower()).strip()


def load_existing(path):
    try:
        import yaml  # type: ignore
    except ImportError:
        sys.exit("Merging with the existing publications.yml needs PyYAML:  pip install pyyaml\n"
                 "(or run again with --replace to ignore the old file).")
    data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or []
    return [dict(x) for x in data]


def merge(new, old):
    old_by_title = {norm(o.get("title", "")): o for o in old}
    used, merged = set(), []
    for d in new:
        o = old_by_title.get(norm(d["title"]))
        if o:
            used.add(norm(d["title"]))
            for k, v in o.items():
                d.setdefault(k, v)
        merged.append(d)
    kept = [o for o in old if norm(o.get("title", "")) not in used]
    return merged, kept


def sort_items(items):
    pub = [d for d in items if d["type"] == "published"]
    work = [d for d in items if d["type"] != "published"]
    pub.sort(key=lambda d: (0 if "year" not in d else 1, -(int(d["year"]) if str(d.get("year", "")).isdigit() else 0)))
    areas = []
    for d in work:
        if d.get("area") not in areas:
            areas.append(d.get("area"))
    work.sort(key=lambda d: areas.index(d.get("area")))
    return pub + work


def main():
    ap = argparse.ArgumentParser(description="Convert a .bib file into publications.yml")
    ap.add_argument("bib", help="BibTeX file (e.g. exported from Zotero)")
    ap.add_argument("-o", "--out", default=OUT_DEFAULT, help="output file (default: publications.yml)")
    ap.add_argument("--replace", action="store_true", help="ignore the existing file; output only what is in the .bib")
    ap.add_argument("--dry-run", action="store_true", help="print the result without writing")
    args = ap.parse_args()

    entries = parse_bib(Path(args.bib).read_text(encoding="utf-8"))
    if not entries:
        sys.exit("No entries found in the .bib file.")
    items = [convert(e) for e in entries]
    items = [d for d in items if d.get("title")]

    kept = []
    out = Path(args.out)
    if not args.replace and out.exists():
        items, kept = merge(items, load_existing(out))
    items = sort_items(items + kept)

    text = HEADER + dump(items)
    n_pub = sum(1 for d in items if d["type"] == "published")
    if args.dry_run:
        print(text)
    else:
        if out.exists():
            shutil.copyfile(out, out.with_suffix(out.suffix + ".bak"))
        out.write_text(text, encoding="utf-8")
    print(f"{len(items)} papers ({n_pub} published, {len(items) - n_pub} working); "
          f"{len(entries)} from the .bib, {len(kept)} kept from the old file.", file=sys.stderr)
    for d in kept:
        print(f"  kept (not in .bib): {d['title'][:80]}", file=sys.stderr)


if __name__ == "__main__":
    main()
